### ISSUE TITLE
Redis example doesn't compile in TypeScript

### ISSUE THREAD

**Issue by maxpain** [ravangen/graphql-rate-limit#280]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/5875582/154481289-bae175f8-415e-41bb-81cc-fc9ec8ff5a5f.png">

**Comment by ravangen** [comment]
@maxpain thanks for the bug report. I saw it yesterday, but wasn't able to get to it right away.

This should be fixed in `2.0.1` by passing in a second generic argument to `rateLimitDirective`, such as `IRateLimiterStoreOptions`

**Comment by abhiche** [comment]
@ravangen I followed the Redis example and I got the same error as @maxpain.
The TS error went away after using the below config.
But my requests are timing out.

```
const maxWrongAttemptsByIPperDay = 10;
const limiterSlowBruteByIP = new RateLimiterRedis({
  storeClient: redisClient,
  keyPrefix: 'login_fail_ip_per_day',
  points: maxWrongAttemptsByIPperDay,
  duration: 60,
  blockDuration: 60, // Block for 1 min, if 10 wrong attempts per min
});
const { rateLimitDirectiveTypeDefs, rateLimitDirectiveTransformer } =
  rateLimitDirective({
    limiterOptions: limiterSlowBruteByIP,
  });
```

**Comment by ravangen** [comment]
I'll try to take a closer look at the example in a couple days, but at a quick glance I see two suspicious things in your code:
- `redis@4.5.1` is not supported per [docs](https://github.com/animir/node-rate-limiter-flexible/wiki/Redis): `It supports ioredis package and redis package version <= 3. It is not adapted for redis version 4 yet, legacyMode should be used for it.`
- `limiterOptions` is not receiving the [right value](https://github.com/ravangen/graphql-rate-limit/blob/00f4f2b7b1e39658340009d9eb521ee3838dfe90/src/index.ts#L133-L136). It is expected to be object with keys like `storeClient`, but rejects `points` and `duration` as `graphql-rate-limit-directive` is responsible for setting those values on a per field basis.

**Comment by vincent-paing** [comment]
@ravangen I'm using `ioredis` and still see this type error

![Screenshot 2023-02-09 at 12 40 50 PM](https://user-images.githubusercontent.com/8557241/217727758-fa38faf3-5921-40a4-9732-c84f20be81b3.png)

**Comment by ravangen** [comment]
Can you provide a reproduction repo, or at least share the versions of the packages you are using.

I don't have plans to support `ioredis` as I am short on time currently, but contributions are welcome.

**Comment by nathanchapman** [comment]
@vincent-paing I'm also using `ioredis`. Explicitly passing the type worked for me:
(also detailed in [the fix PR](https://github.com/ravangen/graphql-rate-limit/pull/286))
```ts
const { rateLimitDirectiveTypeDefs, rateLimitDirectiveTransformer } = rateLimitDirective<
        GraphQLContext,
        IRateLimiterRedisOptions
    >({
        limiterClass: RateLimiterRedis,
        limiterOptions: {
            storeClient: redisClient,
        },
        ...
    });
```
